name: Quabbity Assuance

on: [pull_request]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install --with dev
      - name: Run Ruff
        run: |
          poetry run ruff check .
      - name: Run Tests
        run: |
          poetry run pytest
